Author: Alex Rousskov <rousskov@measurement-factory.com> Do not zero the destination set in CpuAnd() replacement for CPU_AND()
because the destination set may be one of the source sets. This fixes

   ERROR: invalid CPU affinity for process PID 17935, may be caused by
   an invalid core in 'cpu_affinity_map' or by external affinity
   restrictions

errors on systems with partial CPU affinity support lacking their own CPU_AND.

based on 3p2-plus r10834.